version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-samp-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v83pimlze6vs"
s3_prefix = "demo-samp-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
