Description:  This template deploys an Application Load Balancer in Public Subnets

Metadata: 
  AWS::CloudFormation::Interface: 
     ParameterGroups: 
      - 
        Label: 
          default: "Environment Configuration"
        Parameters: 
          - EnvironmentName
      - 
        Label: 
          default: "Network Configuration"      
        Parameters: 
          - VPC
          - PublicSubnet1
          - PublicSubnet2
          - ALBSecurityGroup
      - 
        Label: 
          default: "ALB Attributes"      
        Parameters: 
          - LogBucket
          - EnableDeletionProtection
    
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  #VPC Configurtion
  VPC : 
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription : must be the VPC Id of an existing Virtual Private Cloud.
    Type : AWS::EC2::VPC::Id

  PublicSubnet1:
    Description : Subnet ID from one AZ
    ConstraintDescription: must be valid value of existing subnet id from the selected Virtual Private Cloud
    Type: AWS::EC2::Subnet::Id
  
  PublicSubnet2:
    Description : Subnet ID 2 from another AZ
    ConstraintDescription: must be valid value of existing subnet id from the selected Virtual Private Cloud
    Type: AWS::EC2::Subnet::Id

  ALBSecurityGroup:
   Description : Select the SecurityGroup Associated with ALB
   Type: AWS::EC2::SecurityGroup::Id


  LogBucket:
    Description : Specify the Existing S3 bucket
    Default: logs.ecsparkhybrid.com
    Type: String

  EnableDeletionProtection:
    Description: Recommended to enable deletion protection for PROD environment
    Type: String
    Default: false
    AllowedValues:
     - false
     - true   

Resources:
  ALB:
   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
   Properties: 
    LoadBalancerAttributes:
     - Key: access_logs.s3.enabled
       Value: true
     - Key : access_logs.s3.bucket
       Value : !Ref LogBucket
     - Key : access_logs.s3.prefix
       Value : !Sub ${EnvironmentName}
     - Key: deletion_protection.enabled
       Value: !Ref EnableDeletionProtection
    SecurityGroups:
     - !Ref ALBSecurityGroup
    Subnets: 
     - !Ref PublicSubnet1
     - !Ref PublicSubnet2
    Tags: 
     - Key: Name
       Value: !Ref EnvironmentName

 
  HTTPlistener:
   Type: "AWS::ElasticLoadBalancingV2::Listener"
   Properties:
     DefaultActions:
       - Type: "redirect"
         RedirectConfig:
           Protocol: "HTTPS"
           Port: "443"
           Host: "#{host}"
           Path: "/#{path}"
           Query: "#{query}"
           StatusCode: "HTTP_301"
     LoadBalancerArn: !Ref ALB
     Port: 80
     Protocol: "HTTP"

         
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
     Name: !Sub '${EnvironmentName}-Web-TG'
     Port: 80
     Protocol: HTTP
     TargetGroupAttributes:
      - Key: stickiness.enabled
        Value: true
     VpcId: !Ref VPC
     Tags: 
      - Key: Name
        Value: !Ref EnvironmentName 


Outputs:
  ALB:
    Description: ALB DNS Name
    Value: !GetAtt ALB.DNSName